### ISSUE TITLE
HP Z23i doesn't work

### ISSUE THREAD

**Issue by huctorvigo** [florianbeck/BrightnessMenulet#1]
Hello,
inacho's version works but it has not keyboard bindings, your version has but it doesn't change brightness:)
Thanks

https://github.com/inacho/BrightnessMenulet

**Comment by florianbeck** [comment]
Hi, 
inacho's version is very different so i could not figure out why it is not working with your monitor. Since i'm not owning this monitor i could not debug the code for this device. 
Greetings

**Comment by huctorvigo** [comment]
ok. thank you
