### ISSUE TITLE
Allow auto-follow to be calibrated

### ISSUE THREAD

**Issue by wagenet** [florianbeck/BrightnessMenulet#11]
My external display's 0 setting is much brighter than my MacBook's 0 setting. It would be nice to correct for this in the auto-follow settings, e.g. 30 on the internal is 0 on the external.

**Comment by florianbeck** [comment]
This feature is added with commit f38ea26dd00e5a44aab28952954673df22597603. 
**Note**: You can use negative values as well. For me MIN -10, MAX 100 worked well.

**Comment by cseelus** [comment]
This utility is awesome and works on my Dell U2515H like a charm. Thanks a lot!
